param(
    [Parameter(Mandatory = $true)]
    [string]$Root
)

$ErrorActionPreference = 'Stop'
$rootPath = [System.IO.Path]::GetFullPath($Root)
$propsPath = Join-Path $rootPath 'Version.props'
if (-not (Test-Path -LiteralPath $propsPath)) {
    throw "Version.props was not found at $propsPath"
}

[xml]$props = Get-Content -LiteralPath $propsPath -Raw
$ns = [System.Xml.XmlNamespaceManager]::new($props.NameTable)
$ns.AddNamespace('m', 'http://schemas.microsoft.com/developer/msbuild/2003')

function Read-VersionPart([string]$name) {
    $node = $props.SelectSingleNode("/m:Project/m:PropertyGroup/m:$name", $ns)
    if ($null -eq $node -or [string]::IsNullOrWhiteSpace($node.InnerText)) {
        throw "Missing $name in Version.props"
    }
    $value = 0
    if (-not [int]::TryParse($node.InnerText.Trim(), [ref]$value) -or $value -lt 0 -or $value -gt 65535) {
        throw "$name must be an integer between 0 and 65535"
    }
    return $value
}

$major = Read-VersionPart 'VmpVersionMajor'
$minor = Read-VersionPart 'VmpVersionMinor'
$patch = Read-VersionPart 'VmpVersionPatch'
$build = Read-VersionPart 'VmpVersionBuild'
$version = "$major.$minor"
$fourPart = "$major.$minor.$patch.$build"

$generatedDir = Join-Path $rootPath 'generated'
New-Item -ItemType Directory -Force -Path $generatedDir | Out-Null
$headerPath = Join-Path $generatedDir 'Version.h'
$headerLines = @(
    '#pragma once',
    '// Generated by tools/SyncVersion.ps1 from Version.props. Do not edit by hand.',
    "#define VMP_VERSION_MAJOR $major",
    "#define VMP_VERSION_MINOR $minor",
    "#define VMP_VERSION_PATCH $patch",
    "#define VMP_VERSION_BUILD $build",
    "#define VMP_VERSION_FILE $major,$minor,$patch,$build",
    ('#define VMP_VERSION_STR "' + $version + '"'),
    ('#define VMP_VERSION_RC_STR "' + $version + '\0"'),
    ('#define VMP_VERSION_WSTR L"' + $version + '"'),
    ('#define VMP_VERSION_FOUR_PART_STR "' + $fourPart + '"')
)
# rc.exe is stricter than cl.exe about a preprocessor file ending without a newline.
# Keep this generated header ASCII + CRLF and always terminate the final line.
$header = [string]::Join("`r`n", $headerLines) + "`r`n"
[System.IO.File]::WriteAllText($headerPath, $header, [System.Text.Encoding]::ASCII)

$manifestPaths = @(
    (Join-Path $rootPath 'Portable\Source\app.manifest'),
    (Join-Path $rootPath 'Installer\Source\app.manifest'),
    (Join-Path $rootPath 'Installer\Installer\setup.manifest')
)
foreach ($manifestPath in $manifestPaths) {
    if (-not (Test-Path -LiteralPath $manifestPath)) { throw "Manifest not found: $manifestPath" }
    $text = [System.IO.File]::ReadAllText($manifestPath)
    $manifestRegex = [regex]::new('(<assemblyIdentity\s+version=")[^"]+("\s+processorArchitecture=)')
    $updated = $manifestRegex.Replace($text, "`${1}$fourPart`${2}", 1)
    $expectedToken = 'version="' + $fourPart + '"'
    if ($updated -eq $text -and $text -notmatch [regex]::Escape($expectedToken)) {
        throw "Could not update assemblyIdentity version in $manifestPath"
    }
    [System.IO.File]::WriteAllText($manifestPath, $updated, ([System.Text.UTF8Encoding]::new($false)))
}

Write-Host "VisualMediaPlayer version synchronized: $version"
